steps:
- id: "Store Values"
  name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
    - -c 
    - |
      # store multiple values as environment variables
      # name all values with a common prefix (we'll use "build_")
      if [ "$BRANCH_NAME" = "master" ]
      then
        export build_profile="ngsaas-test"
      elif [ "$BRANCH_NAME" = "prod" ]
      then
        export build_profile="ngsaas-prod"
      else
        export build_profile="ngsaas-dev"
      fi

      export build_prefix="" 

      # write all "build_" variables to the persistent volume "/workspace"
      env | grep "^build_" > /workspace/build_vars
      cat /workspace/build_vars
# move on to the next step; everything in the environment is discarded,
# EXCEPT items on the "/workspace" mount

- id: "Read Values"
  name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
    - -c
    - |
      # Read environment variables from disk
      source /workspace/build_vars &&
      
      # All "build_" values are now available in the environment of this step
      echo "My profile is $build_profile and my Prefix is $build_prefix."